name: madtsanda_platform

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: madtsanda_platform_app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - '3333:3333'
    depends_on:
      mysql-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rustfs:
        condition: service_started

  mysql-db:
    image: mysql:8.0
    container_name: madtsanda_platform_database
    restart: unless-stopped
    env_file:
      - .env.production # <--- TAMBAHKAN INI agar MySQL bisa membaca ${MYSQL_ROOT_PASSWORD} dll.
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 10

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs_server
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    env_file:
      - .env.production # <--- TAMBAHKAN INI agar RustFS bisa membaca ${RUSTFS_ACCESS_KEY} dll.
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
      RUSTFS_ADDRESS: ':9000'
      RUSTFS_CONSOLE_ENABLE: 'true'
    volumes:
      - rustfs_data:/var/lib/rustfs_data

  redis:
    image: redis:7-alpine
    container_name: redis_server
    restart: unless-stopped
    env_file:
      - .env.production # <--- TAMBAHKAN INI agar Redis bisa membaca ${REDIS_PASSWORD}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a "$${REDIS_PASSWORD}" ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  rustfs_data:
  redis_data: