services:
  mysql-db:
    image: mysql:8.0
    container_name: madtsanda_platform_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1141140203
      MYSQL_DATABASE: madtsanada_platform_database
      MYSQL_USER: super_user
      MYSQL_PASSWORD: 1141140203
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
