/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  Students: () => import('#controllers/students_controller'),
  Teachers: () => import('#controllers/teachers_controller'),
  Users: () => import('#controllers/users_controller'),
  NewsCategories: () => import('#controllers/news_categories_controller'),
  News: () => import('#controllers/news_controller'),
}
