/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NewsSchema extends BaseModel {
  static $columns = ['categoryId', 'content', 'createdAt', 'id', 'imageKey', 'imageUrl', 'pin', 'title', 'updatedAt', 'userId'] as const
  $columns = NewsSchema.$columns
  @column()
  declare categoryId: string | null
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageKey: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare pin: boolean | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class NewsCategorySchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'updatedAt'] as const
  $columns = NewsCategorySchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ResearchSchema extends BaseModel {
  static $columns = ['abstrack', 'createdAt', 'documentKey', 'documentUrl', 'id', 'publishedDate', 'researchTagId', 'status', 'title', 'updatedAt', 'userId'] as const
  $columns = ResearchSchema.$columns
  @column()
  declare abstrack: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare documentKey: string
  @column()
  declare documentUrl: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare publishedDate: string | null
  @column()
  declare researchTagId: string | null
  @column()
  declare status: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class ResearchTagSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'updatedAt'] as const
  $columns = ResearchTagSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['address', 'class', 'createdAt', 'gender', 'grade', 'id', 'nis', 'nisn', 'phone', 'profileKey', 'profileUrl', 'status', 'ttl', 'updatedAt', 'userId'] as const
  $columns = StudentSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare class: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gender: string | null
  @column()
  declare grade: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nis: string | null
  @column()
  declare nisn: string | null
  @column()
  declare phone: string | null
  @column()
  declare profileKey: string | null
  @column()
  declare profileUrl: string | null
  @column()
  declare status: string | null
  @column()
  declare ttl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class TeacherSchema extends BaseModel {
  static $columns = ['academicHandles', 'academicTitle', 'address', 'createdAt', 'gender', 'id', 'phone', 'profileKey', 'profileUrl', 'secondaryEmail', 'ttl', 'updatedAt', 'userId'] as const
  $columns = TeacherSchema.$columns
  @column()
  declare academicHandles: string | null
  @column()
  declare academicTitle: string | null
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare gender: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare phone: string | null
  @column()
  declare profileKey: string | null
  @column()
  declare profileUrl: string | null
  @column()
  declare secondaryEmail: string | null
  @column()
  declare ttl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'password', 'role', 'updatedAt', 'username'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string | null
}
