/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type NewsCategoryTransformer from '#transformers/news_category_transformer'
import type NewsTransformer from '#transformers/news_transformer'
import type StudentTransformer from '#transformers/student_transformer'
import type TeacherTransformer from '#transformers/teacher_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type NewsCategory = InferData<NewsCategoryTransformer>
  export namespace NewsCategory {
    export type Variants = InferVariants<NewsCategoryTransformer>
  }
  export type News = InferData<NewsTransformer>
  export namespace News {
    export type Variants = InferVariants<NewsTransformer>
  }
  export type Student = InferData<StudentTransformer>
  export namespace Student {
    export type Variants = InferVariants<StudentTransformer>
  }
  export type Teacher = InferData<TeacherTransformer>
  export namespace Teacher {
    export type Variants = InferVariants<TeacherTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
